name: Sync Leetcode Solutions
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Sync
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{secrets['LeetCode Token']}}
          leetcode-csrf-token: ${{secrets.LEETCODE_CSRF_TOKEN}}
          leetcode-session: ${{secrets.LEETCODE_SESSION}}
